version: "3.8"

services:
  node:
    image: 'node:18-alpine'
    restart: always
    ports:
      - "80:5000"
    working_dir: /var/www/front
    command: sh -c "npm install && npm run dev -- --host"
    volumes:
      - ./bashautocom:/var/www/front
    tty: true

    container_name: frontend
